# Default configuration for ai-code
api:
  provider: "groq"
  key: "${GROQ_API_KEY}"
  default_model: "llama-3.3-70b"
  fallback_model: "deepseek-v3"

editor:
  auto_save: true
  backup_count: 5
  syntax_highlighting: true

git:
  auto_commit: false
  commit_prefix: "ai-code:"
  push_after_commit: false

privacy:
  local_mode: false
  data_retention_days: 30
  audit_logging: true
